2019-06-16 23:53:30,753 ERROR: Exception on / [GET] [in /home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/app/routes.py", line 39, in index
    return render_template('index.html', title='Home Page', posts=posts)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/app/templates/index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-06-16 23:54:33,643 ERROR: Exception on / [GET] [in /home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/app/routes.py", line 39, in index
    return render_template('index.html', title='Home Page', posts=posts)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/app/templates/index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-06-17 00:13:22,963 INFO: Microblog startup [in /home/uferepeace/Documents/projects/FlaskMicroBlog/app/__init__.py:46]
2019-06-17 00:22:03,498 INFO: Microblog startup [in /home/uferepeace/Documents/projects/FlaskMicroBlog/app/__init__.py:46]
2019-06-17 00:36:48,905 INFO: Microblog startup [in /home/uferepeace/Documents/projects/FlaskMicroBlog/app/__init__.py:46]
2019-06-17 00:43:34,871 INFO: Microblog startup [in /home/uferepeace/Documents/projects/FlaskMicroBlog/app/__init__.py:46]
2019-06-17 00:49:00,612 INFO: Microblog startup [in /home/uferepeace/Documents/projects/FlaskMicroBlog/app/__init__.py:46]
2019-06-17 00:49:29,978 INFO: Microblog startup [in /home/uferepeace/Documents/projects/FlaskMicroBlog/app/__init__.py:46]
2019-06-17 08:36:59,219 INFO: Microblog startup [in /home/uferepeace/Documents/projects/FlaskMicroBlog/app/__init__.py:48]
2019-06-18 08:30:48,453 INFO: Microblog startup [in /home/uferepeace/Documents/projects/FlaskMicroBlog/app/__init__.py:48]
2019-06-18 08:32:17,427 ERROR: Exception on /reset_password_request [POST] [in /home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/app/routes.py", line 159, in reset_password_request
    send_password_reset_email(user)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/app/email.py", line 12, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/app/models.py", line 65, in get_reset_password_token
    return jwt.encode(
NameError: name 'jwt' is not defined
2019-06-18 08:33:19,348 INFO: Microblog startup [in /home/uferepeace/Documents/projects/FlaskMicroBlog/app/__init__.py:48]
2019-06-18 08:37:28,058 INFO: Microblog startup [in /home/uferepeace/Documents/projects/FlaskMicroBlog/app/__init__.py:48]
2019-06-18 08:52:18,725 INFO: Microblog startup [in /home/uferepeace/Documents/projects/FlaskMicroBlog/app/__init__.py:48]
